Repository adgorithmics-inc/cinnamon-javascript-sdk, pull requests merged in 2019-12, with the labels that each got.

#47 T-295 remove `.npmc` to make circle happy
  .circleci/config.yml
  .npmrc
Labels: Awaiting :馬:, Tests Not Required, Tooling

#49 T-318 add approveMarketingCampaign function
  index.node.js
  index.web.js
  src/generated/graphql.d.ts
  src/generated/graphql.ts
  src/index.d.ts
  src/index.ts
Labels: Awaiting :馬:

#46 T-257 Added support for nested fields
  codegen.yml
  generateFields.js
  index.node.js
  index.web.js
  package-lock.json
  package.json
  src/generated/fields.d.ts
  src/generated/fields.ts
  src/helpers.d.ts
  src/helpers.ts
  src/index.d.ts
  src/index.ts
  src/inputFields/index.d.ts
  src/inputFields/index.ts
  webpack.config.js
Labels: Awaiting :馬:

#53 T-335 build in circle to check build matches
  .circleci/config.yml
Labels: Awaiting :馬:, Tooling

#51 T-331 return raw data in errors
  index.node.js
  index.web.js
  package-lock.json
  package.json
  src/helpers.d.ts
  src/helpers.ts
  src/index.d.ts
  src/index.ts
Labels: Awaiting :馬:

#50 T-322 added function to set refresh token
  index.node.js
  index.web.js
  src/index.d.ts
  src/index.ts
Labels: Awaiting :馬:

#54 T-257 Allow overriding nameMap in getFormattedFields
  index.node.js
  index.web.js
  src/helpers.d.ts
  src/helpers.ts
Labels: Awaiting :馬:, Tests Skipped

#55 Update to latest Cinna API, add string[] types to fields
  src/generated/graphql.d.ts
  src/generated/graphql.ts
  src/index.d.ts
  src/index.ts
Labels: Awaiting :馬:, Tests Not Required

#58 T-341 fix types
  generateFields.js
  index.node.js
  index.web.js
  src/generated/fields.d.ts
  src/generated/fields.ts
  src/helpers.d.ts
  src/helpers.ts
  src/index.d.ts
  src/index.ts
Labels: Awaiting :馬:, Tests Skipped
