Repository adgorithmics-inc/cinnamon-javascript-sdk, pull requests merged in 2020-03, with the labels that each got.

#70 T-485 retry logic
  .eslintrc
  index.node.js
  index.web.js
  package-lock.json
  package.json
  src/helpers.d.ts
  src/helpers.ts
  src/index.d.ts
  src/index.ts
  tests/api.test.ts
Labels: 2 Reviews, Awaiting :馬:, Has Test Coverage

#72 T-494 Add bulk update methods
  index.node.js
  index.web.js
  src/generated/fields.d.ts
  src/generated/fields.ts
  src/generated/graphql.d.ts
  src/generated/graphql.ts
  src/helpers.d.ts
  src/helpers.ts
  src/index.d.ts
  src/index.ts
Labels: 1 Review, Awaiting :馬:, Tests Skipped

#74 NO-TICKET bump adgo errors package
  index.node.js
  index.web.js
  package-lock.json
  package.json
  tests/helpers.test.ts
Labels: 1 Review, Awaiting :馬:
