Repository adgorithmics-inc/cinnamon-javascript-sdk, pull requests merged in 2020-05, with the labels that each got.

#76 T-603 Add syncCatalog mutation and campaignTemplatesWithCurrentGCPX
  index.node.js
  index.web.js
  src/generated/fields.d.ts
  src/generated/fields.ts
  src/generated/graphql.d.ts
  src/generated/graphql.ts
  src/index.d.ts
  src/index.ts
Labels: 1 Review, Awaiting :馬:, Has Dependencies, Tests Skipped

#77 NO-TICKET api update
  index.node.js
  index.web.js
  src/generated/fields.d.ts
  src/generated/fields.ts
  src/generated/graphql.d.ts
  src/generated/graphql.ts
Labels: 1 Review, Awaiting :馬:

#78 Update
  index.node.js
  index.web.js
  src/generated/fields.d.ts
  src/generated/fields.ts
  src/generated/graphql.d.ts
  src/generated/graphql.ts
  src/index.d.ts
  src/index.ts
Labels: 1 Review, Awaiting :馬:

#79 T-646 Replace allPages and eachNode with iterative implementations
  index.node.js
  index.web.js
  src/index.ts
Labels: 1 Review, Awaiting :馬:, Tests Skipped

#80 2.0.0-alpha.1
  .circleci/config.yml
  README.md
  src/generated/graphql.d.ts
  src/generated/graphql.ts
Labels: 1 Review, Awaiting :馬:
